### ISSUE TITLE
[feature request] Arrays with a complex type are not defined in the documentation

### ISSUE THREAD

**Issue by patpicos** [Kavinraja-G/crossplane-docs#11]
XRD Definition:
```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xhelmapplications.gitops.k8s.sourced.io
spec:
  defaultCompositionRef:
    name: xhelmapplication.kcl.aws.gitops.k8s.sourced.io
  group: gitops.k8s.sourced.io
  names:
    kind: XHelmApplication
    plural: xhelmapplications
  claimNames:
    kind: HelmApplication
    plural: helmapplications  
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:  
                      projectName:
                        type: string
                        description: Name of the ArgoCD project to deploy to 
                      destination:
                        type: object
                        description: Reference to the target Kubernetes server and namespace
                        properties:
                          name: 
                            type: string
                            description: Name of the target cluster
                          namespace:
                            type: string
                            description: Target namespace for the application's resources. Applies to any step where a step namespace is not provided.
                          server:
                            type: string
                            description: URL of the target cluster's Kubernetes control plane API 
                        oneOf:
                        - required: [ "namespace", "name" ]
                        - required: [ "namespace", "server" ]        
                      steps:
                        type: array
                        minItems: 1
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of the step to be created
                            destination:
                              type: object
                              description: Destination where the step will be deployed to
                              properties:
                                namespace:
                                  type: string
                                  description: Target namespace for the application's resources. It overrides the parameters.destination.namespace
                            sources:
                              type: array
                              items:
                                type: object
                                properties:  
                                  chart: 
                                    type: string
                                    description: Helm chart name to be used
                                  repoURL:
                                    type: string
                                    description: URL to the repository (Git or Helm) that contains the application manifests
                                  targetRevision:
                                    type: string
                                    description: TargetRevision defines the revision of the source to sync the application to
                                  ref:
                                    type: string
                                    description: Ref is reference to another source within sources field   
                                  helm:
                                    type: object
                                    description: Helm specific options
                                    properties:
                                      releaseName: 
                                        type: string
                                        description: Helm release name to use. If omitted it will use the application name
                                      valueFiles:
                                        type: array
                                        description:  File name and path to be refrenced from other source
                                        items:
                                          type: string
                                required:
                                - repoURL
                                - targetRevision  
                            syncPolicy:
                              type: object
                              description: Custom syncPolicy for each step
                              properties:
                                automated:
                                  type: object
                                  description: Keep an application synced to the target revision
                                  properties:
                                    prune:
                                      type: boolean
                                      description: Whether to delete resources from the cluster that are not found in the sources anymore as part of automated sync
                                      default: false
                                    selfHeal:
                                      type: boolean
                                      description: whether to revert resources back to their desired state upon modification in the cluster
                                      default: true
                                retry:
                                  type: object
                                  description: Controls failed sync retry behavior
                                  properties:
                                    limit:
                                      type: integer
                                      description: The maximum number of attempts for retrying a failed sync. If set to 0, no retries will be performed
                                    backoff:
                                      type: object
                                      description: Controls how to backoff on subsequent retries of failed syncs
                                      properties:
                                        duration:
                                          type: string
                                          description: The amount to back off. Default unit is seconds, but could also be a duration
                                          default: "5s"
                                        maxDuration:
                                          type: string
                                          description: The maximum amount of time allowed for the backoff strategy
                                          default: "3m0s"
                                        factor:
                                          type: integer
                                          description: A factor to multiply the base duration after each failed retry
                                          default: 2                     
                                syncOptions:
                                  type: array
                                  description: Options allow you to specify whole app sync-options
                                  items:
                                    type: string                    
                          required:
                            - name   
                            - sources
                      appsSyncPolicy:
                        type: object
                        description: syncPolicy to be applied to all steps if step doesn't have a custom one
                        properties:
                          automated:
                            type: object
                            description: Keep an application synced to the target revision
                            properties:
                              prune:
                                type: boolean
                                description: Whether to delete resources from the cluster that are not found in the sources anymore as part of automated sync
                                default: false
                              selfHeal:
                                type: boolean
                                description: whether to revert resources back to their desired state upon modification in the cluster
                                default: true
                          retry:
                            type: object
                            description: Controls failed sync retry behavior
                            properties:
                              limit:
                                type: integer
                                description: The maximum number of attempts for retrying a failed sync. If set to 0, no retries will be performed
                              backoff:
                                type: object
                                description: Controls how to backoff on subsequent retries of failed syncs
                                properties:
                                  duration:
                                    type: string
                                    description: The amount to back off. Default unit is seconds, but could also be a duration
                                    default: "5s"
                                  maxDuration:
                                    type: string
                                    description: The maximum amount of time allowed for the backoff strategy
                                    default: "3m0s"
                                  factor:
                                    type: integer
                                    description: A factor to multiply the base duration after each failed retry
                                    default: 2                     
                          syncOptions:
                            type: array
                            items:
                              type: string  
                              description: Options allow you to specify whole app sync-options                                    
                      sequentialAppChart:
                        type: object
                        default: {}
                        description: Refrences the chart that is used to generate child Applications
                        properties:
                          chart:
                            type: string
                            default: "{{ .Values.sequentialAppChart.chart}}"
                          repoURL:
                            type: string
                            default: "{{ .Values.sequentialAppChart.repoURL}}"
                          targetRevision:
                            type: string
                            default: "{{ .Values.sequentialAppChart.targetRevision}}"
                      syncPolicy:
                        type: object
                        description: syncPolicy for the parent Application
                        properties:
                          automated:
                            type: object
                            description: Keep an application synced to the target revision
                            properties:
                              prune:
                                type: boolean
                                description: Whether to delete resources from the cluster that are not found in the sources anymore as part of automated sync
                                default: false
                              selfHeal:
                                type: boolean
                                description: whether to revert resources back to their desired state upon modification in the cluster
                                default: true
                          retry:
                            type: object
                            description: Controls failed sync retry behavior
                            properties:
                              limit:
                                type: integer
                                description: The maximum number of attempts for retrying a failed sync. If set to 0, no retries will be performed
                              backoff:
                                type: object
                                description: Controls how to backoff on subsequent retries of failed syncs
                                properties:
                                  duration:
                                    type: string
                                    description: The amount to back off. Default unit is seconds, but could also be a duration
                                    default: "5s"
                                  maxDuration:
                                    type: string
                                    description: The maximum amount of time allowed for the backoff strategy
                                    default: "3m0s"
                                  factor:
                                    type: integer
                                    description: A factor to multiply the base duration after each failed retry
                                    default: 2                     
                          syncOptions:
                            type: array
                            description: Options allow you to specify whole app sync-options   
                            items:
                              type: string                   
                  required:
                    - projectName     
                    - destination
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS resource.
                  type: object
                  default: {}
                  properties:
                    deletionPolicy:
                      description: Defaults to Orphan
                      enum:
                        - Delete
                        - Orphan
                      type: string  
                      default: Orphan
                    managementPolicies:
                      type: array
                      description: List of actions Crossplane can take on managed resources included in this composition and its corresponding external resources.
                      items:
                        type: string
                        enum:
                        - Create
                        - Delete
                        - LateInitialize
                        - Observe
                        - Update
                      default:
                      - Create
                      - LateInitialize
                      - Observe   
            status:
              properties:
                roleArn:
                  type: string                               

```

Generated Output:
```markdown

### xhelmapplications.gitops.k8s.sourced.io
| Name | Claim |
|------|-------|
| xhelmapplications.gitops.k8s.sourced.io | HelmApplication |
#### Specs
##### Version: v1beta1
| Field | Path | Type | Description | Required |
|------|-------|------|-------|-------|
| spec |  | object |  | false |
| parameters | spec | object |  | false |
| sequentialAppChart | spec.parameters | object | Refrences the chart that is used to generate child Applications | false |
| chart | spec.parameters.sequentialAppChart | string |  | false |
| repoURL | spec.parameters.sequentialAppChart | string |  | false |
| targetRevision | spec.parameters.sequentialAppChart | string |  | false |
| steps | spec.parameters | array |  | false |
| syncPolicy | spec.parameters | object | syncPolicy for the parent Application | false |
| retry | spec.parameters.syncPolicy | object | Controls failed sync retry behavior | false |
| backoff | spec.parameters.syncPolicy.retry | object | Controls how to backoff on subsequent retries of failed syncs | false |
| duration | spec.parameters.syncPolicy.retry.backoff | string | The amount to back off. Default unit is seconds, but could also be a duration | false |
| factor | spec.parameters.syncPolicy.retry.backoff | integer | A factor to multiply the base duration after each failed retry | false |
| maxDuration | spec.parameters.syncPolicy.retry.backoff | string | The maximum amount of time allowed for the backoff strategy | false |
| limit | spec.parameters.syncPolicy.retry | integer | The maximum number of attempts for retrying a failed sync. If set to 0, no retries will be performed | false |
| syncOptions | spec.parameters.syncPolicy | array | Options allow you to specify whole app sync-options | false |
| automated | spec.parameters.syncPolicy | object | Keep an application synced to the target revision | false |
| prune | spec.parameters.syncPolicy.automated | boolean | Whether to delete resources from the cluster that are not found in the sources anymore as part of automated sync | false |
| selfHeal | spec.parameters.syncPolicy.automated | boolean | whether to revert resources back to their desired state upon modification in the cluster | false |
| appsSyncPolicy | spec.parameters | object | syncPolicy to be applied to all steps if step doesn't have a custom one | false |
| automated | spec.parameters.appsSyncPolicy | object | Keep an application synced to the target revision | false |
| prune | spec.parameters.appsSyncPolicy.automated | boolean | Whether to delete resources from the cluster that are not found in the sources anymore as part of automated sync | false |
| selfHeal | spec.parameters.appsSyncPolicy.automated | boolean | whether to revert resources back to their desired state upon modification in the cluster | false |
| retry | spec.parameters.appsSyncPolicy | object | Controls failed sync retry behavior | false |
| backoff | spec.parameters.appsSyncPolicy.retry | object | Controls how to backoff on subsequent retries of failed syncs | false |
| duration | spec.parameters.appsSyncPolicy.retry.backoff | string | The amount to back off. Default unit is seconds, but could also be a duration | false |
| factor | spec.parameters.appsSyncPolicy.retry.backoff | integer | A factor to multiply the base duration after each failed retry | false |
| maxDuration | spec.parameters.appsSyncPolicy.retry.backoff | string | The maximum amount of time allowed for the backoff strategy | false |
| limit | spec.parameters.appsSyncPolicy.retry | integer | The maximum number of attempts for retrying a failed sync. If set to 0, no retries will be performed | false |
| syncOptions | spec.parameters.appsSyncPolicy | array |  | false |
| destination | spec.parameters | object | Reference to the target Kubernetes server and namespace | true |
| name | spec.parameters.destination | string | Name of the target cluster | false |
| namespace | spec.parameters.destination | string | Target namespace for the application's resources. Applies to any step where a step namespace is not provided. | false |
| server | spec.parameters.destination | string | URL of the target cluster's Kubernetes control plane API | false |
| projectName | spec.parameters | string | Name of the ArgoCD project to deploy to | true |
| resourceConfig | spec | object | ResourceConfig defines general properties of this AWS resource. | false |
| deletionPolicy | spec.resourceConfig | string | Defaults to Orphan | false |
| managementPolicies | spec.resourceConfig | array | List of actions Crossplane can take on managed resources included in this composition and its corresponding external resources. | false |
| status |  |  |  | false |
| roleArn | status | string |  | false |

```

Subset of XRD with the array definitions
```yaml
                      steps:
                        type: array
                        minItems: 1
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of the step to be created
                            destination:
                              type: object
                              description: Destination where the step will be deployed to
                              properties:
                                namespace:
                                  type: string
                                  description: Target namespace for the application's resources. It overrides the parameters.destination.namespace
                            sources:
                              type: array
                              items:
                                type: object
                                properties:  
                                  chart: 
                                    type: string
                                    description: Helm chart name to be used
                                  repoURL:
                                    type: string
                                    description: URL to the repository (Git or Helm) that contains the application manifests
                                  targetRevision:
                                    type: string
                                    description: TargetRevision defines the revision of the source to sync the application to
                                  ref:
                                    type: string
                                    description: Ref is reference to another source within sources field   
                                  helm:
                                    type: object
                                    description: Helm specific options
                                    properties:
                                      releaseName: 
                                        type: string
                                        description: Helm release name to use. If omitted it will use the application name
                                      valueFiles:
                                        type: array
                                        description:  File name and path to be refrenced from other source
                                        items:
                                          type: string
                                required:
                                - repoURL
                                - targetRevision  
```
