### ISSUE TITLE
Outputs not rendered correctly

### ISSUE THREAD

**Issue by patpicos** [Kavinraja-G/crossplane-docs#15]
**What happened:**
The attributes under status are not being broken down under the outputs section
Sample definition:
```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnfsservers.gitops.k8s.dish.io
spec:
  defaultCompositionRef:
    name: xnfsserver.kcl.aws.gitops.k8s.dish.io
  group: gitops.k8s.dish.io
  names:
    kind: XNfsServer
    plural: xnfsservers
  claimNames:
    kind: NfsServer
    plural: nfsservers  
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                      availabilityZone:
                        type: string
                        description: The AZ where the EBS volume will exist.
                      size:
                        type: integer
                        description: The size of the drive in GiBs.
                      snapshotId:
                        type: string
                        description: A snapshot to base the EBS volume off of.
                      type:
                        type: string
                        description:  The type of EBS volume. Can be standard, gp2, gp3, io1, io2, sc1 or st1 (Defaults to gp2).
                        default: gp2     
                      subnetId:
                        type: string
                        description: Subnet ID to create the ENI in              
                      vpcId:
                        type: string
                        description:  VPC id where the EC2 instance will be created in.    
                      sourceSecurityGroupId:
                        type: string
                        description: SecurityGroupId of the cluster that has access to this NFS server  
                      amiId:
                        type: string
                        description: AMI id to be used tolaunch the instance
                      instanceType:
                        type: string
                        description: Instance type to be used to launch the instance
                        default: m5.2xlarge   
                      targetDevice:
                        type: string
                        description: Name of the device to mount the data volume on.
                        default: "/dev/sdf"
                      subnetCidr:
                        type: string
                        description: CIDR range for the cluster that has access to this server
                        default: "100.64.96.0/19"
                      subnetGateway:
                        type: string   
                        description: Gateway IP of the subnet the server is created in
                      mountPath:
                        type: string
                        default: "/data"   
                      prismaAccessKeyArn:
                        type: string
                        description: ARN of the prisma access key in Secrets Manager
                        default: "arn:aws:secretsmanager:us-west-2:xxxx:secret:prisma/AccessKey-iizorP"
                      prismaSecretKeyArn:
                        type: string
                        description: ARN of the prisma secret key in Secrets Manager
                        default: "arn:aws:secretsmanager:us-west-2:xxxx:secret:prisma/SecretKey-RwwBiU"
                      tags:
                        type: object
                        additionalProperties:
                          type: string      
                  required:
                    - availabilityZone
                    - subnetId
                    - vpcId
                    - sourceSecurityGroupId
                    - amiId
                    - subnetGateway
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS resource.
                  type: object
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string  
                    managementPolicies:
                      type: array
                      description: List of actions Crossplane can take on managed resources included in this composition and its corresponding external resources.
                      items:
                        type: string
                        enum:
                        - Create
                        - Delete
                        - LateInitialize
                        - Observe
                        - Update
                      default:
                      - Create
                      - LateInitialize
                      - Observe
                    region:
                      type: string    
                  required:
                  - region    
            status:
              properties:
                serverIp:
                  type: string   
                  description: Private IP address of network interface 
                          
```
**What you expected to happen:**
Presence of `serverIp` field in the outputs

**How to reproduce it (as minimally and precisely as possible):**
v0.1.3 and use the above definition.
Current outcome:
```markdown

### xnfsservers.gitops.k8s.dish.io
| Name | Claim |
|------|-------|
| xnfsservers.gitops.k8s.dish.io | NfsServer |
#### Specs
##### Version: v1beta1
##### Inputs
| Field | Path | Type | Description | Default |  Required |
|------|-------|------|-------|-------|-------|
| spec |  | object |  | n/a | false |
| parameters | spec | object |  | n/a | false |
| prismaSecretKeyArn | spec.parameters | string | ARN of the prisma secret key in Secrets Manager | "arn:aws:secretsmanager:us-west-2:xxxx:secret:prisma/SecretKey-RwwBiU" | false |
| sourceSecurityGroupId | spec.parameters | string | SecurityGroupId of the cluster that has access to this NFS server | n/a | true |
| subnetId | spec.parameters | string | Subnet ID to create the ENI in | n/a | true |
| tags | spec.parameters | object |  | n/a | false |
| vpcId | spec.parameters | string | VPC id where the EC2 instance will be created in. | n/a | true |
| amiId | spec.parameters | string | AMI id to be used tolaunch the instance | n/a | true |
| size | spec.parameters | integer | The size of the drive in GiBs. | n/a | false |
| subnetCidr | spec.parameters | string | CIDR range for the cluster that has access to this server | "100.64.96.0/19" | false |
| instanceType | spec.parameters | string | Instance type to be used to launch the instance | "m5.2xlarge" | false |
| subnetGateway | spec.parameters | string | Gateway IP of the subnet the server is created in | n/a | true |
| type | spec.parameters | string | The type of EBS volume. Can be standard, gp2, gp3, io1, io2, sc1 or st1 (Defaults to gp2). | "gp2" | false |
| mountPath | spec.parameters | string |  | "/data" | false |
| prismaAccessKeyArn | spec.parameters | string | ARN of the prisma access key in Secrets Manager | "arn:aws:secretsmanager:us-west-2:xxxx:secret:prisma/AccessKey-iizorP" | false |
| snapshotId | spec.parameters | string | A snapshot to base the EBS volume off of. | n/a | false |
| targetDevice | spec.parameters | string | Name of the device to mount the data volume on. | "/dev/sdf" | false |
| availabilityZone | spec.parameters | string | The AZ where the EBS volume will exist. | n/a | true |
| resourceConfig | spec | object | ResourceConfig defines general properties of this AWS resource. | n/a | false |
| deletionPolicy | spec.resourceConfig | string | Defaults to Delete | n/a | false |
| managementPolicies | spec.resourceConfig | array | List of actions Crossplane can take on managed resources included in this composition and its corresponding external resources. | ["Create","LateInitialize","Observe"] | false |
| region | spec.resourceConfig | string |  | n/a | true |
##### Outputs
| Field | Path | Type | Description | Default |  Required |
|------|-------|------|-------|-------|-------|
| status |  |  |  | n/a | false |

```

**Anything else we need to know?**
