### ISSUE TITLE
No content being generated

### ISSUE THREAD

**Issue by patpicos** [Kavinraja-G/crossplane-docs#7]
I tried running crossplane docs from a few paths and everytime the readme returns empty.

Structure:
```bash
$ pwd                                                                                                                                                                                                                                                                               
/home/k8s/crossplane/templates/apis

$ tree                                                                                                                                                                                                                                                                              
.
├── XArgoCluster
│   ├── aws-kcl-composition.yaml
│   └── definition.yaml
├── XCluster
│   ├── aws-kcl-composition.yaml
│   └── definition.yaml
├── XEFS
│   ├── aws-kcl-composition.yaml
│   └── definition.yaml
├── XHelmApplication
│   ├── aws-kcl-composition.yaml
│   └── definition.yaml
├── XIrsa
│   ├── aws-kcl-composition.yaml
│   └── definition.yaml
├── XLambda
│   ├── aws-composition.yaml
│   └── definition.yaml
├── XMultus
│   ├── aws-kcl-composition.yaml
│   └── definition.yaml
├── XNodeGroup
│   ├── aws-kcl-composition.yaml
│   └── definition.yaml
├── XNodeTerminationHandler
│   ├── aws-kcl-composition.yaml
│   └── definition.yaml
├── XVelero
│   ├── aws-kcl-composition.yaml
│   └── definition.yaml
├── gitlab.gitops.k8s.dish.io
│   ├── XLdapGroupLink
│   │   ├── definition.yaml
│   │   └── rest-kcl-composition.yaml
│   └── XProjectJobTokenPermission
│       ├── definition.yaml
│       └── rest-kcl-composition.yaml
├── ldap.gitops.k8s.dish.io
│   └── XGroup
│       ├── definition.yaml
│       └── rest-kcl-composition.yaml
└── onboarding.gitops.k8s.dish.io
    ├── XCnfOnboarding
    │   ├── definition.yaml
    │   └── kcl-composition.yaml
    ├── XIsvContinuousDeployment
    │   ├── definition.yaml
    │   └── kcl-composition.yaml
    └── XIsvContinuousIntegration
        ├── definition.yaml
        └── kcl-composition.yaml

20 directories, 32 files
```

Note: our compositions use KCL lang. At a minimum, i am interested in having the XRD definition documented.
```bash
➜  apis git:(main) crossplane-docs -v                                                                                                                                                                                                                                                              
crossplane-docs version 0.1.2

➜  apis git:(main) crossplane-docs markdown ./XCluster -o XRD_README.md      
                                                                                                                                                                                                                        
➜  apis git:(main) ✗ cat XRD_README.md                                                                                                                                                                                                                                                               

```

**Comment by Kavinraja-G** [comment]
@patpicos Thanks for looking into this tool! Is it possible for you to share a sample `definition.yaml` (redacted) one that you are trying to gen docs for?

**Comment by patpicos** [comment]
Here's an example 
```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xefss.gitops.k8s.sourced.io
spec:
  defaultCompositionRef:
    name: xefs.kcl.aws.gitops.k8s.sourced.io
  group: gitops.k8s.sourced.io
  names:
    kind: XEFS
    plural: xefss
  claimNames:
    kind: EFS
    plural: efss  
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    creationToken:
                      description: A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System
                      type: string 
                    availabilityZoneName:
                      description: AWS Availability Zone in which to create the file system. Used to create a file system that uses One Zone storage classes.
                      type: string
                    encrypted:
                      type: boolean
                      description: If true, the disk will be encrypted.
                      default: true  
                    enableBackup:
                      type: boolean
                      description: A flag to enable or disable backup policy
                      default: true  
                    kmsKeyId:
                      description: The ARN for the KMS encryption key
                      type: string
                    performanceMode:
                      type: string
                      description: The file system performance mode. Can be either 'generalPurpose' or 'maxIO' (Defaults to 'generalPurpose').
                      enum:
                      - generalPurpose
                      - maxIO  
                      default: generalPurpose
                    throughputMode:
                      type: string
                      description: Throughput mode for the file system. Defaults to elastic.
                      enum:
                      -  bursting
                      -  provisioned
                      -  elastic
                      default: elastic
                    provisionedThroughputInMibps:
                      type: integer
                      description: The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with throughput_mode set to provisioned.  
                    securityGroup:
                      type: object
                      properties:
                        vpcId:
                          type: string
                        rules:
                          type: array
                          minItems: 1
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                                description: Unique name to identify the sg rule
                              fromPort:
                                type: integer
                                default: 2049
                              toPort:
                                type: integer
                                default: 2049
                              cidrBlocks:
                                type: array
                                minItems: 1
                                items:
                                  type: string
                              sourceSecurityGroupId:
                                type: string  
                            oneOf:    
                            - required: ["name","cidrBlocks"]
                            - required: ["name","sourceSecurityGroupId"]

                      required: 
                      - vpcId            
                    accessPoints:
                      description: List of access points to be created
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Unique name to identify the access point
                          posixUser:
                            type: object
                            default: {}
                            properties:
                              gid:
                                type: integer
                                description: POSIX group ID used for all file system operations using this access point.
                                default: 1000
                              uid:
                                type: integer
                                description: POSIX user ID used for all file system operations using this access point.
                                default: 1000  
                          rootDirectory:
                            type: object
                            description: Directory on the Amazon EFS file system that the access point provides access to
                            default: {}
                            properties:
                              path:
                                type: string
                                description: Path on the EFS file system to expose as the root directory
                                default: "/"
                              creationInfo:
                                type: object
                                default: {}
                                description: POSIX IDs and permissions to apply to the access point's Root Directory. 
                                properties:
                                  ownerGid:
                                    type: integer
                                    description: POSIX group ID to apply to the root_directory.
                                    default: 1000
                                  ownerUid:
                                    type: integer
                                    description: POSIX user ID to apply to the root_directory.
                                    default: 1000
                                  permissions:
                                    type: string
                                    description: POSIX permissions to apply to the RootDirectory, in the format of an octal number representing the file's mode bits.
                                    default: "750"  
                        required:
                        - name
                    mountTargets:
                      description: List of mount targets to be created
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Unique name to identify the mount target
                          subnetId:
                            type: string
                            description: The ID of the subnet to add the mount target in.
                          securityGroups:
                            type: array
                            decsription: List of security groups to be added to mount target
                            items:
                              type: string  
                          ipAddress:
                            type: string
                            description: The address (within the address range of the specified subnet) at which the file system may be mounted via the mount target.
                        required:
                        - name
                        - subnetId        
                    tags:
                      type: object
                      additionalProperties:
                        type: string   
                    dynamicProvisioning:
                      type: object
                      default: {}
                      x-kubernetes-validations:
                      - rule: " !has(self.enabled) || !self.enabled || (has(self.kubernetesProviderConfigRefName) && size(self.storageClasses) > 0)"
                        message: Provider config name is required when dynamic provisioning is enabled                      
                      properties:
                        enabled:
                          type: boolean
                          description: Flag to enable dynamic provisioning and creating StorageClass
                          default: false    
                        kubernetesProviderConfigRefName:
                          type: string
                          description: Name of the kubernetes provider config to create the StorageClass in.
                        storageClasses:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                                description: name of the StorageClass
                              directoryPerms:
                                type: string
                                default: "700"
                              basePath:
                                type: string
                                default: "/dynamic_provisioning"    
                              reclaimPolicy:
                                type: string
                                enum:
                                - Retain
                                - Delete
                                default: Retain   
                            required:
                            - name                               
                  required:
                    - securityGroup
                resourceConfig:
                  type: object
                  properties:
                    region:
                      description: Geographic location of this bucket
                      type: string
                    deletionPolicy:
                      description: Defaults to Orphan
                      enum:
                        - Delete
                        - Orphan
                      type: string 
                      default: Orphan 
                    managementPolicies:
                      type: array
                      description: List of actions Crossplane can take on managed resources included in this composition and its corresponding external resources.
                      items:
                        type: string
                        enum:
                        - Create
                        - Delete
                        - LateInitialize
                        - Observe
                        - Update
                      default:
                      - Create
                      - LateInitialize
                      - Observe                      
                  required:
                    - region
              required:
                - resourceConfig
            status:
              type: object
              properties:
                fileSystemId:
                  type: string    

```
